### ISSUE TITLE
Render only failing snapshots in report

### ISSUE THREAD

**Issue by bytasv** [NimaSoroush/differencify-jest-reporter#1]
Hello,

is it possible to render only failing snapshots to the report?

As I understand reporter renders all test results but we would like to getonly failing snapshots so we can output that in the CI / github commits

**Comment by NimaSoroush** [comment]
Hi @bytasv , yes, that is a good idea actually. Possibly would be great to introduce a new flag for that feature. like `failingOnly`. what do you think?

```
reporters: [
    'default', // keep the default reporter
    [
      'differencify-jest-reporter',
      {
        debug: true,
        outPutType: failingOnly,
        reportPath: 'differencify_reports',
        reportTypes: {
          html: 'index.html',
          json: 'index.json',
        },
      },
    ],
  ],
```

**Comment by bytasv** [comment]
Yeah, that should work!

**Comment by NimaSoroush** [comment]
Great, Do you mind adding a PR for it?

**Comment by bytasv** [comment]
If I will find some spare time, I could. Right now it's fairly low in our priority list

**Comment by NimaSoroush** [comment]
Thanks for raising the PR
